# Generated by Django 3.0.3 on 2020-11-11 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('status', models.CharField(default='1', max_length=100)),
                ('priority', models.CharField(default='1', max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('priority', models.CharField(default='1', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
                ('corpAddressLine1', models.CharField(max_length=100)),
                ('corpAddressLine2', models.CharField(max_length=100)),
                ('corpCity', models.CharField(max_length=100)),
                ('corpState', models.IntegerField()),
                ('corpZipcode', models.CharField(default='1', max_length=100)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
                ('zipcode', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('pay_rate', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('start_date', models.CharField(default='1', max_length=100)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('total', models.FloatField(default='')),
                ('dueDate', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('job_id', models.IntegerField(default=69)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('category_id', models.CharField(default='1', max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('employee_id', models.CharField(default='1', max_length=100)),
                ('job_id', models.CharField(default='1', max_length=100)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('dueDate', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TimesheetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_num', models.CharField(max_length=100)),
                ('time_start', models.TimeField(default='01:00')),
                ('time_end', models.TimeField(default='01:00')),
                ('status', models.CharField(default='1', max_length=100)),
                ('sheet_id', models.CharField(default='1', max_length=100)),
                ('employee_id', models.CharField(default='1', max_length=100)),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('content_projectNum', models.FloatField(default=1234.21)),
                ('content_timeStart', models.TimeField(default='01:00')),
                ('content_timeEnd', models.TimeField(default='01:00')),
                ('content_totalHours', models.FloatField(default=0.15)),
                ('content_userID', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(related_name='blog_posts_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='blog_posts_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('budget', models.FloatField(default='')),
                ('description', models.CharField(default='1', max_length=1024)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('jobCustomer', models.IntegerField()),
                ('status', models.CharField(default='1', max_length=100)),
                ('orders', models.ManyToManyField(related_name='job_orders', to='blog.OrderModel')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
