# Generated by Django 3.0.3 on 2020-11-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201111_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='priority',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
