# Generated by Django 3.0.3 on 2020-11-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201111_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='job_id',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
