# Generated by Django 3.0.3 on 2020-11-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201111_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='total',
        ),
    ]
