# Generated by Django 3.0.3 on 2020-11-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_ordermodel_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='title',
        ),
    ]
