# Generated by Django 3.0.3 on 2020-11-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201111_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='1', max_length=100)),
                ('product_id', models.CharField(default='1', max_length=100)),
                ('quantity', models.CharField(default='1', max_length=100)),
                ('price', models.CharField(default='1', max_length=100)),
                ('total', models.CharField(default='1', max_length=100)),
                ('priority', models.CharField(default='1', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
            ],
            options={
                'verbose_name': 'Orderline',
                'verbose_name_plural': 'Orderlines',
            },
        ),
    ]
