# Generated by Django 3.0.3 on 2020-11-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_orderlinemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlinemodel',
            name='total',
        ),
    ]
