# Generated by Django 3.0.3 on 2020-11-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_orderlinemodel_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobassignmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default='1', max_length=100)),
                ('job_id', models.CharField(default='1', max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Job Assignment',
                'verbose_name_plural': 'Job Assignments',
            },
        ),
    ]
