# Generated by Django 3.0.3 on 2020-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_jobassignmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignmentmodel',
            name='status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
