from django.urls import path
from .views import (PostListView, 
                    AllPostListView, 
                    LatestPostListView, 
                    AnnouncementPostListView, 
                    TimesheetPostListView, 
                    AllTimesheetPostListView, 
                    TaskAssignmentPostListView, 
                    AllTaskAssignmentPostListView,
                    PostDetailView, 
                    PostCreateView, 
                    PostCreateAnnouncementView, 
                    PostCreateTimesheetView, 
                    PostCreateNewClientView, 
                    PostCreateTaskAssignmentView, 
                    PostUpdateView, 
                    PostDeleteView, 
                    UserPostListView, 
                    LikeView, 
                    DislikeView, 
                    SQLView,
                    create_job,
                    create_announcement,
                    create_product,
                    create_task,
                    job_detail,
                    job_detail_sql,
                    announcement_detail_sql,
                    timesheet_detail_sql,
                    task_detail_sql,
                    timesheet_detail,
                    announcement_detail,
                    product_detail,
                    product_detail_sql,
                    task_detail,
                    employee_detail,
                    employee_detail_sql,
                    all_jobs,
                    create_customer,
                    create_employee,
                    customer_detail,
                    customer_detail_sql,
                    all_customers,
                    create_order,
                    update_timesheet,
                    order_detail_sql,
                    all_orders,
                    all_timesheets,
                    all_announcements,
                    all_tasks,
                    all_products,
                    all_employees,
                    all_customers_sql,
                    all_jobs_sql,
                    all_employees_sql,
                    all_products_sql,
                    all_announcements_sql,
                    all_tasks_sql,
                    all_timesheets_sql,
                    all_orders_sql,
                    create_order_sql,
                    PostListView_sql,
                    portal_view,
                    home_employee_view,
                    home_admin_view,
                    delete_timesheet,
                    create_timesheet_test,
                    update_task,
                    delete_task,
                    update_announcement,
                    delete_announcement,
                    update_employee,
                    delete_employee,
                    update_job,
                    delete_job,
                    update_order,
                    delete_order,
                    update_product,
                    delete_product,
                    update_customer,
                    delete_customer,
                    all_queries_sql,
                    orderline_detail_sql,
                    query_detail_sql,
                    export_csv,
                    update_orderline,
                    delete_orderline,
                    create_orderline,
                    create_jobass,
                    update_jobass,
                    all_jobass_sql,
                    jobass_detail_sql,
                    delete_jobass,
                    all_tasks_sql_employee,
                    all_announcements_sql_employee,
                    all_timesheets_sql_employee,
                    all_jobs_sql_employee,
                    timesheet_detail_sql_employee,
                    task_detail_sql_employee,
                    job_detail_sql_employee,
                    announcement_detail_sql_employee,
                    orderline_detail_sql_employee,
                    order_detail_sql_employee,
                    create_timesheet_test_employee,
                    employee_detail_sql_employee,
                    jobcomplaint_detail_sql,
                    create_jobcomplaint,
                    delete_jobcomplaint,
                    update_jobcomplaint,
                    jobcomplaint_detail_sql_employee)
from . import views

urlpatterns = [
    path('', portal_view, name='portal-home'),
    path('', PostListView.as_view(), name='blog-home'),
    path('portal', portal_view, name='portal-home'),
    path('employee_home', home_employee_view, name='employee-home'),
    path('admin_home', home_admin_view, name='admin-home'),
    path('filter/latest', LatestPostListView.as_view(), name='filter-latest'),
    path('filter/all-latest', AllPostListView.as_view(), name='filter-latest-all'),
    path('filter/announcements', AnnouncementPostListView.as_view(), name='filter-announcements'),
    path('filter/timesheets', TimesheetPostListView.as_view(), name='filter-timesheets'),
    path('filter/all-timesheets', AllTimesheetPostListView.as_view(), name='filter-timesheets-all'),
    path('filter/taskassignments', TaskAssignmentPostListView.as_view(), name='filter-tasks'),
    path('filter/all-taskassignments', AllTaskAssignmentPostListView.as_view(), name='filter-tasks-all'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/new-announcement/', PostCreateAnnouncementView.as_view(), name='post-create-announcement'),
    path('post/new-timesheet/', PostCreateTimesheetView.as_view(), name='post-create-timesheet'),
    path('post/new-newclient/', PostCreateNewClientView.as_view(), name='post-create-newclient'),
    path('post/new-taskassignment/', PostCreateTaskAssignmentView.as_view(), name='post-create-taskassignment'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('connect/', SQLView, name='connect-sql'),
    path('post/like/<int:pk>', LikeView, name='like_post'),
    path('post/dislike/<int:pk>', DislikeView, name='dislike_post'),
    
    # Timesheets #
    path('create/timesheet', create_timesheet_test.as_view(), name='create-timesheet'),
    path('create-employee/timesheet', create_timesheet_test_employee.as_view(), name='create-timesheet-employee'),
    path('timesheet/<int:pk>/', timesheet_detail.as_view(), name='timesheet-detail'),
    path('timesheet/all', all_timesheets.as_view(), name='all-timesheets'),
    
    path('timesheet-sql/employee/all', all_timesheets_sql_employee, name='all-timesheets-sql-employee'),
    path('timesheet-sql/<int:pk>/', timesheet_detail_sql, name='timesheet-detail-sql'),
    path('timesheet-sql-employee/<int:pk>/', timesheet_detail_sql_employee, name='timesheet-detail-sql-employee'),
    path('timesheet-sql/all', all_timesheets_sql, name='all-timesheets-sql'),
    path('update/timesheet/<int:pk>', update_timesheet.as_view(), name='update-timesheet'),
    path('delete/timesheet/<int:pk>', delete_timesheet.as_view(), name='delete-timesheet'),
    
    # Products #
    path('create/product', create_product.as_view(), name='create-product'),
    path('product/<int:pk>/', product_detail.as_view(), name='product-detail'),
    path('product/all', all_products.as_view(), name='all-products'),
    
    path('product-sql/all', all_products_sql, name='all-products-sql'),
    path('product-sql/<int:pk>/', product_detail_sql, name='product-detail-sql'),
    path('update/product/<int:pk>', update_product.as_view(), name='update-product'),
    path('delete/product/<int:pk>', delete_product.as_view(), name='delete-product'),
    
    # Announcements #
    path('create/announcement', create_announcement.as_view(), name='create-announcement'),
    path('announcement/<int:pk>/', announcement_detail.as_view(), name='announcement-detail'),
    path('announcement/all', all_announcements.as_view(), name='all-announcements'),
    
    path('announcement-sql/employee/all', all_announcements_sql_employee, name='all-announcements-sql-employee'),
    path('announcement-sql/<int:pk>/', announcement_detail_sql, name='announcement-detail-sql'),
    path('announcement-sql-employee/<int:pk>/', announcement_detail_sql_employee, name='announcement-detail-sql-employee'),
    path('announcement-sql/all', all_announcements_sql, name='all-announcements-sql'),
    path('update/announcement/<int:pk>', update_announcement.as_view(), name='update-announcement'),
    path('delete/announcement/<int:pk>', delete_announcement.as_view(), name='delete-announcement'),
    
    # Tasks #
    path('create/task', create_task.as_view(), name='create-task'),
    path('task/<int:pk>/', task_detail.as_view(), name='task-detail'),
    path('task/all', all_tasks.as_view(), name='all-tasks'),
    
    path('task-sql/employee/all', all_tasks_sql_employee, name='all-tasks-sql-employee'),
    path('task-sql/<int:pk>/', task_detail_sql, name='task-detail-sql'),
    path('task-sql-employee/<int:pk>/', task_detail_sql_employee, name='task-detail-sql-employee'),
    path('task-sql/all', all_tasks_sql, name='all-tasks-sql'),
    path('update/task/<int:pk>', update_task.as_view(), name='update-task'),
    path('delete/task/<int:pk>', delete_task.as_view(), name='delete-task'),
    
    # Jobs #
    path('create/job', create_job.as_view(), name='create-job'),
    path('job/<int:pk>/', job_detail.as_view(), name='job-detail'),
    path('job/all', all_jobs.as_view(), name='all-jobs'),
    
    path('job-sql/employee/all', all_jobs_sql_employee, name='all-jobs-sql-employee'),
    path('job-sql/all', all_jobs_sql, name='all-jobs-sql'),
    path('job-sql/<int:pk>/', job_detail_sql, name='job-detail-sql'),
    path('job-sql-employee/<int:pk>/', job_detail_sql_employee, name='job-detail-sql-employee'),
    path('update/job/<int:pk>', update_job.as_view(), name='update-job'),
    path('delete/job/<int:pk>', delete_job.as_view(), name='delete-job'),
    
    path('create/jobass', create_jobass.as_view(), name='create-jobass'),
    path('jobass-sql/all', all_jobass_sql, name='all-jobass-sql'),
    path('jobass-sql/<int:pk>/', jobass_detail_sql, name='jobass-detail-sql'),
    path('update/jobass/<int:pk>', update_jobass.as_view(), name='update-jobass'),
    path('delete/jobass/<int:pk>', delete_jobass.as_view(), name='delete-jobass'),
    
    # Job Complaint #
    path('job/<int:pk>/jobcomplaint/create/', create_jobcomplaint.as_view(), name='create-jobcomplaint'),
    
    path('jobcomplaint-sql/<int:pk>/', jobcomplaint_detail_sql, name='jobcomplaint-detail-sql'),
    path('jobcomplaint-sql-employee/<int:pk>/', jobcomplaint_detail_sql_employee, name='jobcomplaint-detail-sql-employee'),
    path('update/jobcomplaint/<int:pk>', update_jobcomplaint.as_view(), name='update-jobcomplaint'),
    path('delete/jobcomplaint/<int:pk>', delete_jobcomplaint.as_view(), name='delete-jobcomplaint'),
    
    path('create/jobass', create_jobass.as_view(), name='create-jobass'),
    path('jobass-sql/all', all_jobass_sql, name='all-jobass-sql'),
    path('jobass-sql/<int:pk>/', jobass_detail_sql, name='jobass-detail-sql'),
    path('update/jobass/<int:pk>', update_jobass.as_view(), name='update-jobass'),
    path('delete/jobass/<int:pk>', delete_jobass.as_view(), name='delete-jobass'),
    
    # Orders #
    path('job/<int:pk>/order/create/', create_order.as_view(), name='create-order'),
    path('order/all', all_orders.as_view(), name='all-orders'),
    
    path('create/order', create_order_sql.as_view(), name='create-order-sql'),
    path('order-sql/<int:pk>', order_detail_sql, name='order-detail-sql'),
    path('order-sql-employee/<int:pk>', order_detail_sql_employee, name='order-detail-sql-employee'),
    path('order-sql/all', all_orders_sql, name='all-orders-sql'),
    path('update/order/<int:pk>', update_order.as_view(), name='update-order'),
    path('delete/order/<int:pk>', delete_order.as_view(), name='delete-order'),
    
    # Orderline #
    path('order-sql/<int:pk>/create/orderline', create_orderline.as_view(), name='create-orderline-sql'),
    path('orderline-sql/<int:pk>/', orderline_detail_sql, name='orderline-detail-sql'),
    path('orderline-sql-employee/<int:pk>/', orderline_detail_sql_employee, name='orderline-detail-sql-employee'),
    path('update/orderline/<int:pk>', update_orderline.as_view(), name='update-orderline'),
    path('delete/orderline/<int:pk>', delete_orderline.as_view(), name='delete-orderline'),
    
    # Customers #
    path('create/customer', create_customer.as_view(), name='create-customer'),
    path('customer/<int:pk>/', customer_detail.as_view(), name='customer-detail'),
    path('customer/all', all_customers.as_view(), name='all-customers'),
    
    path('customer-sql/all', all_customers_sql, name='all-customers-sql'),
    path('customer-sql/<int:pk>/', customer_detail_sql, name='customer-detail-sql'),
    path('update/customer/<int:pk>', update_customer.as_view(), name='update-customer'),
    path('delete/customer/<int:pk>', delete_customer.as_view(), name='delete-customer'),
    
    # Employees #
    path('create/employee', create_employee.as_view(), name='create-employee'),
    path('employee/<int:pk>/', employee_detail.as_view(), name='employee-detail'),
    path('employee/all', all_employees.as_view(), name='all-employees'),
    
    path('employee-sql/all', all_employees_sql, name='all-employees-sql'),
    path('employee-sql/<int:pk>/', employee_detail_sql, name='employee-detail-sql'),
    path('employee-sql-employee/<int:pk>/', employee_detail_sql_employee, name='employee-detail-sql-employee'),
    path('update/employee/<int:pk>', update_employee.as_view(), name='update-employee'),
    path('delete/employee/<int:pk>', delete_employee.as_view(), name='delete-employee'),
    
    # Queries
    path('query-sql/all', all_queries_sql, name='all-queries-sql'),
    path('query-sql/<int:pk>/', query_detail_sql, name='query-detail-sql'),
    path('export-csv/<int:pk>/', export_csv, name='export-csv'),
]